import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import { ApolloWrapper } from '@/lib/ApolloWrapper';
import UserContext from '@/context/user/UserContext';
import NotifyContextProvider from '@/context/notification/notifyContext';
import ChatContextProvider, { ChatContext } from '@/context/chat/chatContext';
import TimeAgo from 'javascript-time-ago'

import en from 'javascript-time-ago/locale/en'
import ru from 'javascript-time-ago/locale/ru'

TimeAgo.addDefaultLocale(en)
TimeAgo.addLocale(ru)

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserContext>
          <NotifyContextProvider>
            <ChatContextProvider>
              <ApolloWrapper>
                {children}
              </ApolloWrapper>
            </ChatContextProvider>
          </NotifyContextProvider>
        </UserContext>
      </body>
    </html>
  )
}
