import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import { ApolloWrapper } from '@/lib/ApolloWrapper';
import UserContext from '@/context/user/UserContext';
import NotifyContextProvider from '@/context/notification/notifyContext';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ApolloWrapper>
          <NotifyContextProvider>
            <UserContext>
              {children}
            </UserContext>
          </NotifyContextProvider>
        </ApolloWrapper>
      </body>
    </html>
  )
}
